_format_version: "2.1"
_transform: true

services:
  - name: maishapoa-production-internal-api
    # Use HTTP to avoid SSL certificate issues (Kong handles TLS at edge)
    url: http://maishapoa-production-internal-api.fly.dev
    routes:
      - name: public-customers
        paths:
          - /api/v1/customers
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: false
        preserve_host: true
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          headers: ["Content-Type", "Authorization", "Accept"]
          exposed_headers: ["X-Total-Count"]
          credentials: true
          max_age: 3600
