packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@sentry/cli': true
  prisma: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
