_format_version: "2.1"
_transform: true

services:
  - name: microbima-staging-internal-api
    url: http://microbima-staging-internal-api.internal:3000
    routes:
      - name: public-customers
        paths:
          - /api/v1/customers
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: false
        preserve_host: true
      - name: public-partner-management
        paths:
          - /api/v1/partner-management
        methods:
          - POST
          - DELETE
        strip_path: false
        preserve_host: true
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          headers: ["Content-Type", "Authorization", "Accept"]
          exposed_headers: ["X-Total-Count"]
          credentials: true
          max_age: 3600
      - name: rate-limiting
        config:
          minute: 200
          hour: 2000
          policy: local
      - name: request-size-limiting
        config:
          allowed_payload_size: 10
      - name: response-ratelimiting
        config:
          limits:
            - minute: 200
              policy: local
              fault_tolerant: true
