_format_version: "2.1"
_transform: true

services:
  - name: microbima-staging-internal-api
    # Use Fly.io internal network (faster and more reliable)
    url: http://microbima-staging-internal-api.internal:3000
    routes:
      - name: public-customers
        paths:
          - /api/v1/customers
        methods:
          - GET
          - POST
        strip_path: false
        preserve_host: true
      - name: public-customer-dependants
        paths:
          - /api/v1/customers
        methods:
          - GET
          - POST
        strip_path: false
        preserve_host: true
      - name: public-customer-beneficiaries
        paths:
          - /api/v1/customers
        methods:
          - GET
          - POST
        strip_path: false
        preserve_host: true
      - name: public-partner-management
        paths:
          - /api/v1/partner-management
        methods:
          - POST
          - DELETE
        strip_path: false
        preserve_host: true
      - name: public-sos
        paths:
          - /api/v1/sos
        methods:
          - GET
        strip_path: false
        preserve_host: true
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          headers: ["Content-Type", "Authorization", "Accept"]
          exposed_headers: ["X-Total-Count"]
          credentials: true
          max_age: 3600
